function foo()
  try
    throw Error("cheese")
    return 42
  catch e if e is Error then
    print("caught:", e)
    return 69
  catch e then
    print("something else")
  finally
    print('cleanup')
  end
end

print("GOT:", foo())

